services:
  express-app:
    image: jayzstep/express-app
    ports:
      - 3441:8080
    container_name: express-app

  watchtower:
    image: containrrr/watchtower:armhf-latest
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: express-app
