name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout repository
      uses: actions/checkout@4

      -name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      -name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./express-app
        push:true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-app:latest
